name: Kingdoms
author: Hex_27
version: ${project.version}
softdepend: [WorldGuard, WorldEdit]
description: Conquer lands with a mighty Kingdom!
main: me.leothepro555.kingdoms.Kingdoms
commands:
  kingdoms:
    description: opens help
    aliases: [k, kingdom]